# Generated by Django 6.0.6 on 2026-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_aifeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aifeedback',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
    ]
