# Generated by Django 6.0.6 on 2026-06-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyresource',
            old_name='topic',
            new_name='topic_name',
        ),
    ]
